version: 2
jobs:
  test:
    machine:
      node:
        version: 8.9.0
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    dependencies:
      pre:
        - npm --version
        - npm i @angular/cli@latest -g
        - npm i firebase-tools -g

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: ng lint
      - run: ng test

  deploy:
    machine:
      node:
        version: 8.9.0
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    dependencies:
      pre:
        - npm --version
        - npm i @angular/cli@latest -g
        - npm i firebase-tools -g

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    deployment:
      # production:
      #   branch: master
      #   commands:
      #     - ng build --prod
      #     - firebase use production
      #     - firebase deploy --token=$FIREBASE_TOKEN --non-interactive
      dev:
        branch: master
        commands:
          - ng build --prod -e=dev
          - firebase use staging
          - firebase deploy --token=$FIREBASE_TOKEN --non-interactive

  # test:
  #   override:
  #     - ng lint
  #     - ng test

  # deployment:
  #   production:
  #     branch: master
  #     commands:
  #       - ng build --prod
  #       - firebase use production
  #       - firebase deploy --token=$FIREBASE_TOKEN --non-interactive
  #   dev:
  #     branch: master
  #     commands:
  #       - ng build --prod -e=dev
  #       - firebase use staging
  #       - firebase deploy --token=$FIREBASE_TOKEN --non-interactive

  # notify:
    # webhooks:
      # A list of hashes representing hooks. Only the url field is supported.
      # - url: https://someurl.com/hooks/circle

